name: response_parser
description: Response Parser makes it easier to parse data and error response from server
version: 1.1.2
repository: https://github.com/Maksimka101/response_parser
issue_tracker: https://github.com/Maksimka101/response_parser/issues

environment:
  sdk: ">=2.17.3 <4.0.0"

dev_dependencies:
  lints: ">=2.0.0 <4.0.0"
  mocktail: ^0.3.0
  test: ^1.16.0

dependencies: 
  fpdart: ^1.0.0
